# Chapter 2 Mathematical Modeling of Control Systems

## Obtaining Cascaded, Parallel, and Feedback (Closed-Loop) Transfer Functions with MATLAB

*   series(sys1, sys2)	Return the series connection sys2 * sys1 for –> sys1 –> sys2 –>.
*   parallel(sys1, sys2)	Return the parallel connection sys1 + sys2.
*   feedback(sys1[, sys2, sign])	Feedback interconnection between two I/O systems.
*   negate(sys)	Return the negative of a system.

$G_1(s)=\frac{10}{s^2+2s+10}$  

$G_2(s)=\frac{5}{s+5}$  

$G_1(s)G_2(s)=\frac{10}{s^2+2s+10}*\frac{5}{s+5}$  

In [2]:
import numpy as np # arrays
import matplotlib.pyplot as plt # plots 
%config InlineBackend.figure_format='retina' # high-res plots

import control as ct # control systems library

In [3]:
num_1=[10]
den_1=[1, 2, 10]
G_1=ct.tf(num_1,den_1)
print("G_1=")
display(G_1)
# print("G_1=",G_1)

num_2=[5]
den_2=[1, 5]
G_2=ct.tf(num_2,den_2)
print("G_2=")
display(G_2)

G_1=


TransferFunction(array([10]), array([ 1,  2, 10]))

G_2=


TransferFunction(array([5]), array([1, 5]))

In [4]:
G_1_serial_G_2=ct.series(G_1,G_2)
print("G_1_serial_G_2=")
display(G_1_serial_G_2)

G_1_serial_G_2=


TransferFunction(array([50]), array([ 1,  7, 20, 50]))

In [5]:
G_1_parallel_G_2=ct.parallel(G_1,G_2)
print("G_1_parallel_G_2=")
display(G_1_parallel_G_2)

G_1_parallel_G_2=


TransferFunction(array([  5,  20, 100]), array([ 1,  7, 20, 50]))

In [6]:
G_1_feedback_G_2=ct.feedback(G_1,G_2)
print("G_1_feedback_G_2=")
display(G_1_feedback_G_2)

G_1_feedback_G_2=


TransferFunction(array([10, 50]), array([  1,   7,  20, 100]))

MATLAB Program 2–2 page 41

In [7]:
num_3=[1]
den_3=[1,14,56,160]
G_3=ct.tf(num_3,den_3)
display(G_3)
G_3_SS=ct.tf2ss(G_3)
display(G_3_SS)
[A,B,C,D]=ct.ssdata(G_3_SS)
display(A,B,C,D)


TransferFunction(array([1]), array([  1,  14,  56, 160]))

StateSpace(array([[ -14.,  -56., -160.],
       [   1.,    0.,    0.],
       [   0.,    1.,    0.]]), array([[1.],
       [0.],
       [0.]]), array([[0., 0., 1.]]), array([[0.]]))

array([[ -14.,  -56., -160.],
       [   1.,    0.,    0.],
       [   0.,    1.,    0.]])

array([[1.],
       [0.],
       [0.]])

array([[0., 0., 1.]])

array([[0.]])

In [8]:
# num = [[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]]
# den = [[[9., 8., 7.], [6., 5., 4.]], [[3., 2., 1.], [-1., -2., -3.]]]
sys1 = ct.tf2ss(num_3, den_3)
display(sys1)
# sys_tf = ct.tf(num, den)
# sys2 = ct.tf2ss(sys_tf)

StateSpace(array([[ -14.,  -56., -160.],
       [   1.,    0.,    0.],
       [   0.,    1.,    0.]]), array([[1.],
       [0.],
       [0.]]), array([[0., 0., 1.]]), array([[0.]]))

Python Calculate a little difference with matlab result

In [9]:
A = np.array([[0. ,1. ,0.],[0., 0., 1.] ,[-5., -25. ,-5.]])
print(A)
B = np.array([[0.], [25.] ,[-120.]])
print(B)
C = np.array([1., 0. ,0.])
print(C)
D = np.array([0.])
print(D)
G_4=ct.ss2tf(A,B,C,D)
[num,den]=ct.tfdata(G_4)
display(G_4)
display([num,den])

[[  0.   1.   0.]
 [  0.   0.   1.]
 [ -5. -25.  -5.]]
[[   0.]
 [  25.]
 [-120.]]
[1. 0. 0.]
[0.]


TransferFunction(array([-1.77635684e-15,  2.50000000e+01,  5.00000000e+00]), array([ 1.,  5., 25.,  5.]))

[[[array([-1.77635684e-15,  2.50000000e+01,  5.00000000e+00])]],
 [[array([ 1.,  5., 25.,  5.])]]]

In [10]:
num=[25,5]
den=[1,5,25,5]
display(ct.tf(num,den))
[A,B,C,D]=ct.ssdata(ct.tf2ss(num,den))


TransferFunction(array([25,  5]), array([ 1,  5, 25,  5]))

In [16]:
A = [[0,1,0],[0,0, 1] ,[-5,-25,-5]]
print(A)
B = [[0], [25] ,[-120]]
print(B)
C = [1, 0 ,0]
print(C)
D = [0]
print(D)
G_4=ct.ss(A,B,C,D)
display(G_4)
[num,den]=ct.tfdata(G_4)
G_5=ct.ss2tf(G_4)
display(G_5)

[[0, 1, 0], [0, 0, 1], [-5, -25, -5]]
[[0], [25], [-120]]
[1, 0, 0]
[0]


<LinearIOSystem:sys[28]:['u[0]']->['y[0]']>

TransferFunction(array([-1.77635684e-15,  2.50000000e+01,  5.00000000e+00]), array([ 1.,  5., 25.,  5.]))

In [12]:
from scipy.signal import ss2tf
ss2tf(A, B, C, D)

(array([[ 0.00000000e+00, -1.77635684e-15,  2.50000000e+01,
          5.00000000e+00]]),
 array([ 1.,  5., 25.,  5.]))

In [13]:
A = [[1., -2], [3, -4]]
display(A)
B = [[5.], [7]]
display(B)
C = [[6., 8]]
display(C)
D = [[9.]]
display(D)
sys1 = ct.ss2tf(A, B, C, D)
display(sys1)
sys_ss = ct.ss(A, B, C, D)
display(sys_ss)
sys2 = ct.ss2tf(sys_ss)
display(sys2)

[[1.0, -2], [3, -4]]

[[5.0], [7]]

[[6.0, 8]]

[[9.0]]

TransferFunction(array([  9., 113., 118.]), array([1., 3., 2.]))

<LinearIOSystem:sys[20]:['u[0]']->['y[0]']>

TransferFunction(array([  9., 113., 118.]), array([1., 3., 2.]))