# check-controllability-and-observability

Example to check the controllability and the observability of a state space system.
RMM, 6 Sep 2010


In [24]:
import numpy as np  # Load the scipy functions
import control as ct  # Load the controls systems library
from sympy import Matrix

# Parameters defining the system

m = 250.0  # system mass
k = 40.0   # spring constant
b = 60.0   # damping constant

# System matrices
A = np.array([[1, -1, 1.],
             [1, -k/m, -b/m],
             [1, 1, 1]])

B = np.array([[0],
             [1/m],
             [1]])

C = np.array([[1., 0, 1.]])

sys = ct.ss(A, B, C, 0)

# Check controllability
Wc = ct.ctrb(A, B)
display("Wc = ", Wc)
# np.linalg.matrix_rank(Wc)

# Check Observability
Wo = ct.obsv(A, C)
display("Wo = ", Wo)

'Wc = '

matrix([[ 0.       ,  0.996    ,  2.24064  ],
        [ 0.004    , -0.24064  ,  0.7935424],
        [ 1.       ,  1.004    ,  1.75936  ]])

'Wo = '

matrix([[1.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [2.00000000e+00, 0.00000000e+00, 2.00000000e+00],
        [4.00000000e+00, 1.11022302e-16, 4.00000000e+00]])

In [18]:

a = np.array([[5, 4, 2, 1], [0, 1, -1, -1], [-1, -1, 3, 0], [1, 1, -1, 2]])
m = Matrix(a)
display("m")
display(m)
m_a=np.mat(a)
display('m_a')
display(m_a)




'm'

Matrix([
[ 5,  4,  2,  1],
[ 0,  1, -1, -1],
[-1, -1,  3,  0],
[ 1,  1, -1,  2]])

'm_a'

matrix([[ 5,  4,  2,  1],
        [ 0,  1, -1, -1],
        [-1, -1,  3,  0],
        [ 1,  1, -1,  2]])

In [19]:
P, J = m.jordan_form()
display(J)
display(type(J))
display(P)
# J_J=m_a.jordan
# display(J_J)



Matrix([
[1, 0, 0, 0],
[0, 2, 0, 0],
[0, 0, 4, 1],
[0, 0, 0, 4]])

sympy.matrices.dense.MutableDenseMatrix

Matrix([
[-1,  1,  1, 1],
[ 1, -1,  0, 0],
[ 0,  0, -1, 0],
[ 0,  1,  1, 0]])

In [32]:
Gs = ct.tf2ss([1], [1, 3, 2])
display(Gs)
Gc, T = ct.canonical_form(Gs)  # default reachable
display(Gc.A)
display(Gc.B)
display(Gc.C)
display(Gc.D)
Gc, T = ct.canonical_form(Gs, 'observable')
display(Gc.A)
display(Gc.B)
display(Gc.C)
display(Gc.D)
# Gc, T = ct.canonical_form(Gs, 'modal')
# display(Gc.A)
# display(Gc.B)
# display(Gc.C)
# display(Gc.D)

StateSpace(array([[-3., -2.],
       [ 1.,  0.]]), array([[1.],
       [0.]]), array([[0., 1.]]), array([[0.]]))

matrix([[-3., -2.],
        [ 1.,  0.]])

matrix([[1.],
        [0.]])

matrix([[0., 1.]])

matrix([[0.]])

matrix([[-3.,  1.],
        [-2.,  0.]])

matrix([[0.],
        [1.]])

matrix([[1., 0.]])

matrix([[0.]])