# 论numpy中matrix 和 array的区别  
Numpy matrices必须是2维的,但是 numpy arrays (ndarrays) 可以是多维的（1D，2D，3D····ND）. Matrix是Array的一个小的分支，包含于Array。所以matrix 拥有array的所有特性。

在numpy中matrix的主要优势是：相对简单的乘法运算符号。例如，a和b是两个matrices，那么a*b，就是矩阵积。

In [25]:
import numpy as np
 
a=np.mat('4 3; 2 1')
b=np.mat('1 2; 3 4')
print("a")
print(a)
print("b")
print(b)
print("a*b")
print(a*b)

a
[[4 3]
 [2 1]]
b
[[1 2]
 [3 4]]


matrix 和 array 都可以通过objects后面加.T 得到其转置。但是 matrix objects 还可以在后面加 .H f得到共轭矩阵, 加 .I 得到逆矩阵。

相反的是在numpy里面arrays遵从逐个元素的运算，所以array：c 和d的c*d运算相当于matlab里面的c.*d运算。

In [26]:
c=np.array([[4, 3], [2, 1]])
d=np.array([[1, 2], [3, 4]])
print("c*d")
print(c*d)

c*d
[[4 6]
 [6 4]]


而矩阵相乘，则需要numpy里面的dot命令 :

In [6]:
print(np.dot(c,d))

[[13 20]
 [ 5  8]]


 ** 运算符的作用也不一样 ：

In [7]:
print(a**2)

print(c**2)

[[22 15]
 [10  7]]
[[16  9]
 [ 4  1]]


因为a是个matrix，所以a**2返回的是a*a，相当于矩阵相乘。而c是array，c**2相当于，c中的元素逐个求平方。

问题就出来了，如果一个程序里面既有matrix 又有array，会让人脑袋大。但是如果只用array，你不仅可以实现matrix所有的功能，还减少了编程和阅读的麻烦。

当然你可以通过下面的两条命令轻松的实现两者之间的转换：np.asmatrix和np.asarray

对我来说，numpy 中的array与numpy中的matrix，matlab中的matrix的最大的不同是，在做归约运算时，array的维数会发生变化，但matrix总是保持为2维。例如下面求平均值的运算

In [9]:
m = np.mat([[1,2],[2,3]])
m

matrix([[1, 2],
        [2, 3]])

In [11]:
mm = m.mean(1)
mm

matrix([[1.5],
        [2.5]])

In [12]:
mm.shape

(2, 1)

In [13]:
m - mm

matrix([[-0.5,  0.5],
        [-0.5,  0.5]])

对array 来说

In [14]:
a = np.array([[1,2],[2,3]])
a

array([[1, 2],
       [2, 3]])

In [16]:
am = a.mean(1)
print(am.shape)
print(am)

(2,)
[1.5 2.5]


In [17]:
a - am #wrong

array([[-0.5, -0.5],
       [ 0.5,  0.5]])

In [18]:
a - am[:, np.newaxis]  #right

array([[-0.5,  0.5],
       [-0.5,  0.5]])